services:
  # Define a service called "db" that will run our PostgreSQL database
  db:
    # Use PostgreSQL version 17.0 as the base image
    image: postgres:17.0
    # Set the hostname to "localhost" so it's easily accessible
    hostname: localhost
    # Port mapping: maps port 5432 on your host machine to port 5432 in the container
    # Format is "host_port:container_port"
    ports:
      - "5432:5432"
    # Environment variables needed to configure PostgreSQL
    environment:
      # Set the database password from your .env file
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # Set the database user from your .env file
      - POSTGRES_USER=${DB_USER}
      # Set the database name from your .env file
      - POSTGRES_DB=${DB_NAME}
    # Mount a volume to persist database data beyond the container lifecycle
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define named volumes that Docker will manage
volumes:
  # "pgdata" volume stores PostgreSQL data files
  # This ensures your database data persists even if the container is removed
  pgdata:
# If looking up the image setup of postgres 17.0, it should include everything above. find it here: https://hub.docker.com/_/postgres?tab=tags&page=1&ordering=last_updated
# in the Terminal, run the following command to start the PostgreSQL database:
# docker compose up
